In [2]:
text="""Data plays a vital role in our everyday life.
Directly or indirectly, for daily life decisions, we depend on some data, be it choosing a novel to read from a list of books, buying a thing after considering the budget, and so on.
Have you ever imagined searching for something on Google or Yahoo generates a lot of data?
This data is essential to analyze user experiences.
Getting recommendations on various e-commerce websites after buying a product and tracking parcels during delivery are part of Data Analytics which involves analyzing the raw data to make informed decisions.
But this raw data does not help make decisions if it has some redundancy, inconsistency, or inaccuracy.
Therefore, this data needs to be cleaned before considering for analysis."""

In [3]:
pip install tensorflow

In [4]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
#Initiate the Tokenizer
tokenizer= Tokenizer()


In [6]:
tokenizer.fit_on_texts([text])

In [7]:
#word count
len(tokenizer.word_index)

87

In [8]:
len(text)  #latter count

757

In [9]:
for sentence in text.split('\n'):
  print(sentence)

Data plays a vital role in our everyday life.
Directly or indirectly, for daily life decisions, we depend on some data, be it choosing a novel to read from a list of books, buying a thing after considering the budget, and so on.
Have you ever imagined searching for something on Google or Yahoo generates a lot of data?
This data is essential to analyze user experiences.
Getting recommendations on various e-commerce websites after buying a product and tracking parcels during delivery are part of Data Analytics which involves analyzing the raw data to make informed decisions.
But this raw data does not help make decisions if it has some redundancy, inconsistency, or inaccuracy.
Therefore, this data needs to be cleaned before considering for analysis.


In [10]:
for sentence in text.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0])

[1, 21, 2, 22, 23, 24, 25, 26, 10]
[27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4, 34, 35, 2, 36, 8, 37, 14, 2, 38, 15, 16, 17, 39, 18, 40, 3]
[41, 42, 43, 44, 45, 6, 46, 3, 47, 5, 48, 49, 2, 50, 8, 1]
[9, 1, 51, 52, 4, 53, 54, 55]
[56, 57, 3, 58, 59, 60, 61, 15, 14, 2, 62, 18, 63, 64, 65, 66, 67, 68, 8, 1, 69, 70, 71, 72, 17, 19, 1, 4, 20, 73, 7]
[74, 9, 19, 1, 75, 76, 77, 20, 7, 78, 13, 79, 11, 80, 81, 5, 82]
[83, 9, 1, 84, 4, 12, 85, 86, 16, 6, 87]


In [11]:
input_sequences=[]
for sentence in text.split('\n'):
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])


In [12]:
input_sequences

[[1, 21],
 [1, 21, 2],
 [1, 21, 2, 22],
 [1, 21, 2, 22, 23],
 [1, 21, 2, 22, 23, 24],
 [1, 21, 2, 22, 23, 24, 25],
 [1, 21, 2, 22, 23, 24, 25, 26],
 [1, 21, 2, 22, 23, 24, 25, 26, 10],
 [27, 5],
 [27, 5, 28],
 [27, 5, 28, 6],
 [27, 5, 28, 6, 29],
 [27, 5, 28, 6, 29, 10],
 [27, 5, 28, 6, 29, 10, 7],
 [27, 5, 28, 6, 29, 10, 7, 30],
 [27, 5, 28, 6, 29, 10, 7, 30, 31],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4, 34],
 [27, 5, 28, 6, 29, 10, 7, 30, 31, 3, 11, 1, 12, 13, 32, 2, 33, 4, 34, 35],


In [13]:
max_len=max([len(x) for x in input_sequences])
max_len

34

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [15]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  1, 21],
       [ 0,  0,  0, ...,  1, 21,  2],
       [ 0,  0,  0, ..., 21,  2, 22],
       ...,
       [ 0,  0,  0, ..., 85, 86, 16],
       [ 0,  0,  0, ..., 86, 16,  6],
       [ 0,  0,  0, ..., 16,  6, 87]], dtype=int32)

In [16]:
X=padded_input_sequences[:,:-1]
y=padded_input_sequences[:,-1]

In [17]:
X

array([[ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  1, 21],
       [ 0,  0,  0, ...,  1, 21,  2],
       ...,
       [ 0,  0,  0, ..., 12, 85, 86],
       [ 0,  0,  0, ..., 85, 86, 16],
       [ 0,  0,  0, ..., 86, 16,  6]], dtype=int32)

In [18]:
y

array([21,  2, 22, 23, 24, 25, 26, 10,  5, 28,  6, 29, 10,  7, 30, 31,  3,
       11,  1, 12, 13, 32,  2, 33,  4, 34, 35,  2, 36,  8, 37, 14,  2, 38,
       15, 16, 17, 39, 18, 40,  3, 42, 43, 44, 45,  6, 46,  3, 47,  5, 48,
       49,  2, 50,  8,  1,  1, 51, 52,  4, 53, 54, 55, 57,  3, 58, 59, 60,
       61, 15, 14,  2, 62, 18, 63, 64, 65, 66, 67, 68,  8,  1, 69, 70, 71,
       72, 17, 19,  1,  4, 20, 73,  7,  9, 19,  1, 75, 76, 77, 20,  7, 78,
       13, 79, 11, 80, 81,  5, 82,  9,  1, 84,  4, 12, 85, 86, 16,  6, 87],
      dtype=int32)

In [19]:
tokenizer.word_index

{'data': 1,
 'a': 2,
 'on': 3,
 'to': 4,
 'or': 5,
 'for': 6,
 'decisions': 7,
 'of': 8,
 'this': 9,
 'life': 10,
 'some': 11,
 'be': 12,
 'it': 13,
 'buying': 14,
 'after': 15,
 'considering': 16,
 'the': 17,
 'and': 18,
 'raw': 19,
 'make': 20,
 'plays': 21,
 'vital': 22,
 'role': 23,
 'in': 24,
 'our': 25,
 'everyday': 26,
 'directly': 27,
 'indirectly': 28,
 'daily': 29,
 'we': 30,
 'depend': 31,
 'choosing': 32,
 'novel': 33,
 'read': 34,
 'from': 35,
 'list': 36,
 'books': 37,
 'thing': 38,
 'budget': 39,
 'so': 40,
 'have': 41,
 'you': 42,
 'ever': 43,
 'imagined': 44,
 'searching': 45,
 'something': 46,
 'google': 47,
 'yahoo': 48,
 'generates': 49,
 'lot': 50,
 'is': 51,
 'essential': 52,
 'analyze': 53,
 'user': 54,
 'experiences': 55,
 'getting': 56,
 'recommendations': 57,
 'various': 58,
 'e': 59,
 'commerce': 60,
 'websites': 61,
 'product': 62,
 'tracking': 63,
 'parcels': 64,
 'during': 65,
 'delivery': 66,
 'are': 67,
 'part': 68,
 'analytics': 69,
 'which': 70,
 'invo

In [20]:
from tensorflow.keras.utils import to_categorical

In [21]:
y=to_categorical(y,num_classes=88)  #total_num(87)+1

In [22]:
y.shape

(119, 88)

In [23]:
X.shape

(119, 33)

#Model building

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [36]:
model=Sequential()
model.add(Embedding(88,100,input_length=33))
model.add(LSTM(150))
model.add(Dense(88,activation='softmax'))


/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [37]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
X.shape

(119, 33)

In [40]:
y.shape

(119, 88)

In [41]:
model.fit(X,y,epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.0168 - loss: 4.4774
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.0588 - loss: 4.4563
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.0588 - loss: 4.4223
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.0588 - loss: 4.3208
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.0588 - loss: 4.2911
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.0588 - loss: 4.2238
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.0504 - loss: 4.1826
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.0420 - loss: 4.1152
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0504 - loss: 4.0448
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.0588 - loss: 3.9959
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0504 - loss: 3.9390
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0756 - lo

#*Test the model*

In [42]:
text2="Data"
# tokenization
token_text = tokenizer.texts_to_sequences([text2])[0]
# padding
padded_text = pad_sequences([token_text], maxlen=33, padding='pre')
# model prediction
model.predict(padded_text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step


array([[1.88217546e-05, 1.51015716e-02, 2.62229461e-02, 4.25384287e-03,
        3.02059855e-03, 5.42026795e-02, 1.25048496e-03, 7.14036651e-05,
        2.41549842e-05, 7.70885050e-02, 7.95501910e-05, 4.38516290e-05,
        1.33317383e-03, 5.32938575e-05, 1.52052336e-04, 2.03294927e-04,
        2.87422590e-04, 3.67294415e-04, 7.63772841e-05, 9.59638972e-03,
        1.80946547e-04, 5.93963623e-01, 4.81337029e-03, 1.61701732e-03,
        3.18390346e-04, 7.85161756e-05, 1.17485964e-04, 9.85649240e-06,
        6.59054145e-03, 1.92141801e-04, 8.22726361e-05, 1.04756196e-04,
        7.81567578e-05, 1.58020630e-04, 9.37815785e-05, 1.51853223e-04,
        6.64054678e-05, 8.45072864e-05, 5.17788103e-05, 6.21946892e-05,
        5.47535128e-05, 1.29928885e-05, 1.60732474e-02, 1.03375232e-02,
        4.68259305e-03, 9.88461077e-04, 1.30229906e-04, 4.74339577e-05,
        1.12028565e-05, 1.97687204e-05, 2.24212836e-05, 8.55989382e-02,
        1.16166696e-02, 8.83813482e-04, 4.13204485e-04, 4.116565

In [47]:
import numpy as np
pos=np.argmax(model.predict(padded_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


In [45]:
tokenizer.word_index

{'data': 1,
 'a': 2,
 'on': 3,
 'to': 4,
 'or': 5,
 'for': 6,
 'decisions': 7,
 'of': 8,
 'this': 9,
 'life': 10,
 'some': 11,
 'be': 12,
 'it': 13,
 'buying': 14,
 'after': 15,
 'considering': 16,
 'the': 17,
 'and': 18,
 'raw': 19,
 'make': 20,
 'plays': 21,
 'vital': 22,
 'role': 23,
 'in': 24,
 'our': 25,
 'everyday': 26,
 'directly': 27,
 'indirectly': 28,
 'daily': 29,
 'we': 30,
 'depend': 31,
 'choosing': 32,
 'novel': 33,
 'read': 34,
 'from': 35,
 'list': 36,
 'books': 37,
 'thing': 38,
 'budget': 39,
 'so': 40,
 'have': 41,
 'you': 42,
 'ever': 43,
 'imagined': 44,
 'searching': 45,
 'something': 46,
 'google': 47,
 'yahoo': 48,
 'generates': 49,
 'lot': 50,
 'is': 51,
 'essential': 52,
 'analyze': 53,
 'user': 54,
 'experiences': 55,
 'getting': 56,
 'recommendations': 57,
 'various': 58,
 'e': 59,
 'commerce': 60,
 'websites': 61,
 'product': 62,
 'tracking': 63,
 'parcels': 64,
 'during': 65,
 'delivery': 66,
 'are': 67,
 'part': 68,
 'analytics': 69,
 'which': 70,
 'invo

In [48]:
for word, index in tokenizer.word_index.items():
  if index==pos:
    print(word)

plays


In [50]:
text3 = "Data plays a"

# tokenization
token_text3 = tokenizer.texts_to_sequences([text3])[0]
# padding
padded_text3 = pad_sequences([token_text3], maxlen=33, padding='pre')
# model prediction
model.predict(padded_text3)

pos3 = np.argmax(model.predict(padded_text3))

for word, index in tokenizer.word_index.items():
  if index==pos3:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
vital


In [51]:
text3 = "Data is a vital role in our everyday life"

# tokenization
token_text3 = tokenizer.texts_to_sequences([text3])[0]
# padding
padded_text3 = pad_sequences([token_text3], maxlen=33, padding='pre')
# model prediction
model.predict(padded_text3)

pos3 = np.argmax(model.predict(padded_text3))

for word, index in tokenizer.word_index.items():
  if index==pos3:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
life


#Improvements:


1.   Increasing the LSTM units
2.   Increasing the Dense layers
3.   Increasing the data
4.   Using a pre-trained model on a larger corpus of data
5.   Hyper parameter optimization