In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('/content/spam.csv')

In [3]:
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [6]:
df.Category.value_counts()

,count
Category,
ham,4825
spam,747


In [7]:
df['Spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

,Category,Message,Spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [9]:
df.shape

(5572, 3)

In [12]:
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

#Create bag of words using CountVectorizer

In [16]:
v=CountVectorizer()

In [17]:
X_train_cv=v.fit_transform(X_train.values)
X_test_cv=v.transform(X_test.values)

In [18]:
X_train_cv.shape

(4457, 7726)

In [19]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zoom', 'ú1', '〨ud'], dtype=object)

In [22]:
v.get_feature_names_out()[1771]

'chile'

In [23]:
v.vocabulary_

{'dhoni': 2264,
 'have': 3341,
 'luck': 4236,
 'to': 6916,
 'win': 7502,
 'some': 6265,
 'big': 1331,
 'title': 6898,
 'so': 6253,
 'we': 7403,
 'will': 7499,
 'do': 2347,
 'you': 7687,
 'always': 917,
 'celebrate': 1683,
 'ny': 4841,
 'with': 7530,
 'your': 7693,
 'family': 2747,
 'its': 3754,
 'just': 3861,
 'the': 6794,
 'effect': 2518,
 'of': 4863,
 'irritation': 3733,
 'ignore': 3593,
 'it': 3746,
 'are': 1030,
 'winner': 7512,
 'been': 1275,
 'specially': 6335,
 'selected': 5970,
 'receive': 5597,
 '1000': 249,
 'cash': 1657,
 'or': 4943,
 '2000': 340,
 'award': 1154,
 'speak': 6331,
 'live': 4135,
 'operator': 4930,
 'claim': 1803,
 'call': 1587,
 '087147123779am': 113,
 '7pm': 622,
 'cost': 2000,
 '10p': 256,
 'huh': 3529,
 'lei': 4065,
 'also': 912,
 'where': 7468,
 'piece': 5177,
 'ok': 4885,
 'how': 3505,
 'dear': 2166,
 'did': 2274,
 'chechi': 1737,
 'india': 3655,
 'going': 3155,
 'draw': 2419,
 'series': 6000,
 'after': 838,
 'many': 4332,
 'years': 7662,
 'in': 3634,
 's

In [24]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
np.where(X_train_np[0]!=0)

(array([1331, 2264, 3341, 4236, 6253, 6265, 6898, 6916, 7403, 7499, 7502]),)

#Naive Based classifier

In [27]:
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [28]:
y_pred=model.predict(X_test_cv)

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       970
           1       0.94      0.94      0.94       145

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [32]:
message={"upto 20% of offer on parking"}

In [34]:
msg_cnt=v.transform(message)
model.predict(msg_cnt)

array([1])