<a href="https://colab.research.google.com/github/AishwaryaGhorpade/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is the fundamental package for numerical computing in Python.
It provides:

The ndarray — a fast, memory-efficient N-dimensional array.

Vectorized operations (elementwise) and broadcasting.

Efficient implementations of linear algebra, random sampling, FFTs, reductions, and more.

Interoperability with C/Fortran libraries and other Python packages (Pandas, SciPy, scikit-learn, etc.).

In [55]:
# Installation of numpy
# pip istall numpy

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
b=np.array([1,2,3],dtype=str)
print(b)

['1' '2' '3']


In [7]:
c=np.array([1,2,3],dtype=float)
print(c)

[1. 2. 3.]


In [8]:
print(len(a))

3


In [9]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [10]:
print(len(a2))

2


finding array dimension

In [11]:
a2.ndim

2

a2 = np.array([[1,2,3], [4,5]])
ValueError: setting an array element with a sequence.


In [12]:
a3 = np.array([[1,2,3], [4,5]], dtype=object)
print(a3)


[list([1, 2, 3]) list([4, 5])]


In [13]:
print(type(a3))

<class 'numpy.ndarray'>


shape: get a shape of numpy array.   (col,row)
It tells you how many elements an array has in each dimension.
shape is an attribute of a NumPy array that returns a tuple representing the size of the array along each dimension.

In [56]:
arr1=np.array([1,2,3])
arr1.shape

(3,)

In [15]:
a2.shape

(2, 3)

In [16]:
arr3=np.array([[[1,2,3],[1,2,3]]])
print(arr3)
arr3.shape

[[[1 2 3]
  [1 2 3]]]


(1, 2, 3)

to see particular data type

In [17]:
a.dtype

dtype('int64')

Accessing/Changing specific elements ,rows and columns etc

In [18]:
#get a specific element using []
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr[1,2]

[[1 2 3]
 [4 5 6]]


np.int64(6)

In [19]:
#get a specific row
arr[1,:]

array([4, 5, 6])

In [20]:
#get a specific column
arr[:,1]

array([2, 5])

numpy array are mutable ,we can change the values.

In [21]:
arr[1,2]=40
print(arr)

[[ 1  2  3]
 [ 4  5 40]]


Zeros and ones method in numpy

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
np.zeros((3,3),dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
np.full((2,3),40,dtype=np.int64)

array([[40, 40, 40],
       [40, 40, 40]])

random method

In [28]:
#rand(row,col)
np.random.rand(2,2)

array([[0.75495968, 0.18496545],
       [0.09363162, 0.7550987 ]])

In [29]:
#randint(start,end,size(row,com))
np.random.randint(1,10,size=(3,3))

array([[8, 7, 9],
       [2, 4, 3],
       [4, 3, 8]])

Identity matrix
[[1 0 0]
[0 1 0]
[0 0 1]]

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
a+100

array([101, 102, 103])

In [32]:
a**2

array([1, 4, 9])

In [33]:
a*2

array([2, 4, 6])

In [34]:
a.min()

np.int64(1)

In [35]:
np.min(a)

np.int64(1)

In [36]:
a.max()

np.int64(3)

In [37]:
np.max(a)

np.int64(3)

In [38]:
a.mean()

np.float64(2.0)

In [39]:
a.sum()

np.int64(6)

In [40]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]], dtype=np.int32)
#a = array([[1,2,3],[4,5,6]])
a.shape    # (2,3)



(2, 3)

In [41]:
a.ndim     # 2

2

In [42]:
a.size     # 6

6

In [43]:
a.dtype    # dtype('int32')

dtype('int32')

In [44]:
a.strides  # e.g. (12,4) depending on dtype size

(12, 4)

In [45]:
np.array([1,2,3])
np.array([[1,2],[3,4]], dtype=float)

np.empty((2,3))        # uninitialized memory (fast)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.arange(0,10,2)      # like range but returns array

array([0, 2, 4, 6, 8])

In [47]:
np.linspace(0,1,5)     # 5 values evenly spaced from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
np.eye(3)              # identity matrix 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
a = np.array([1,2,3], dtype=np.float64)
a.astype(np.int32)  # convert dtype

array([1, 2, 3], dtype=int32)

In [50]:
x = np.arange(12).reshape(3,4)
print(x)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
x[0,1]      # 1

np.int64(1)

In [52]:
x[1]        # row 1: array([4,5,6,7])

array([4, 5, 6, 7])

In [53]:
x[:, :2]    # first two columns

array([[0, 1],
       [4, 5],
       [8, 9]])

In [54]:
x[::2, ::-1]# every 2nd row, reverse columns

array([[ 3,  2,  1,  0],
       [11, 10,  9,  8]])